### ISSUE TITLE
EOF bugi jos "/" avaa selaimella

### ISSUE THREAD

**Issue by jazzu** [pikayem/pkm#7]
Tämä on log.Fatal "konfiguraation lukuvirhe". Ikävä jos vahingossa selaimella torppaa väärän osoitteen vuoksi.

**Comment by sytem** [comment]
tuotantodatalla testaamaton korjaus, server.go rivin 38 ( func ReceiveGameStatus ... ) jälkeen
	if r.Method != "POST" {
		w.WriteHeader(http.StatusBadRequest)
		return
	}

ainakin nyt voi avata urlin kaatamatta softaa, testaan vielä kun on csgo käsillä lähettämään dataa

**Comment by sytem** [comment]
korjattu ja testattu että live-data toimii edelleen.
