### ISSUE TITLE
kanavanimen kovakoodaus pois

### ISSUE THREAD

**Issue by sytem** [pikayem/pkm#9]
konffissa voi antaa kanaville nimet, mutta nollauksessa on kovakoodattu cam[1-10]

**Comment by jazzu** [comment]
Tuumaan, että tarviiko tuolla konfiguraatiossa edes noin eksplisiittisesti nimetä tai muuten käsitellä noita kameroita? Fyysinen järjestys kuitenkin määritellään OBS:ssa oikeat USB-laitteet cam1-10 sourceille määräämällä, jonka jälkeen kameroiden-pelaajien käsittelyyn riittää pelaajien looginen istumapaikkanumero 1-5. OBS websocket komentoliikenteen kannalta on sinänsä sama millä nimellä sourceihin osoitetaan, yhtä hyvin ne voisivat olla suoraan joukkuekirjain + paikka, eli A1-5 ja B1-5.
